import { KoliBriDevHelper } from '@kolibri/lib';

KoliBriDevHelper.patchTheme('mapz', {
  'KOL-BUTTON':
    ':host {font-family: BundesSans;display: inline-block;}button {box-sizing: border-box;font-size: var(--kolibri-font-size);cursor: pointer;border-width: 2px;box-shadow: 0 0 0.25em gray;min-height: 44px;min-width: 44px;letter-spacing: 0.02em;font-family: var(--kolibri-font-family);width: inherit;border-radius: var(--kolibri-border-radius);border-style: solid;align-items: center !important;justify-content: center !important;padding: calc(2 * var(--kolibri-spacing));display: flex;gap: var(--kolibri-spacing);transition-duration: 0.5s;transition-property: background-color, color, border-color;}button:focus {outline-color: var(--kolibri-color-outline) !important;outline-offset: 2px !important;outline-style: solid !important;outline-width: 2px !important;}button:disabled {cursor: not-allowed;opacity: 0.5;}button.primary,button.primary:disabled:hover {background-color: var(--kolibri-color-primary);border-color: var(--kolibri-color-primary);color: white;}button.primary:hover,button.primary:focus {color: var(--kolibri-color-primary);}button.secondary,button.secondary:disabled:hover {background-color: var(--kolibri-color-secondary);border-color: var(--kolibri-color-secondary);color: white;}button.secondary:hover,button.secondary:focus {color: var(--kolibri-color-secondary);}button.normal,button.normal:disabled:hover {background-color: var(--kolibri-color-normal);border-color: var(--kolibri-color-normal);color: white;}button.normal:hover,button.normal:focus {color: var(--kolibri-color-normal);}button.danger,button.danger:disabled:hover {background-color: var(--kolibri-color-danger);border-color: var(--kolibri-color-danger);color: white;}button.danger:hover,button.danger:focus {color: var(--kolibri-color-danger);}button.ghost,button.ghost:disabled:hover {background-color: white;border-color: var(--kolibri-color-ghost);color: var(--kolibri-color-ghost);}button.ghost:hover,button.ghost:focus {background-color: var(--kolibri-color-ghost);color: white;}button:hover,button:focus {background-color: white;box-shadow: 0 0 0.25em black;}button:active {outline: 0 !important;box-shadow: none !important;}',
  'KOL-ALERT':
    ':host {font-family: BundesSans;}:host > div {box-sizing: border-box;border-width: var(--kolibri-border-width);border-style: solid;border-radius: var(--kolibri-border-radius);display: table;align-items: center;width: 100%;}div > div {display: table-cell;}div > div:first-child {color: white;width: 2em;text-align: center;}div > div:last-child {padding: var(--kolibri-spacing);}div.border-success {border-color: var(--kolibri-color-success);}div.border-info {border-color: var(--kolibri-color-info);}div.border-error {border-color: var(--kolibri-color-error);}div.border-warning {border-color: var(--kolibri-color-warning);}div.border-success div:first-child {background-color: var(--kolibri-color-success);}div.border-info div:first-child {background-color: var(--kolibri-color-info);}div.border-error div:first-child {background-color: var(--kolibri-color-error);}div.border-warning div:first-child {background-color: var(--kolibri-color-warning);}',
  'KOL-INPUT-TEXT':
    ':host {font-family: BundesSans;}:host input:focus {outline-color: var(--kolibri-color-outline) !important;outline-offset: 2px;outline-style: solid;outline-width: 3px;}label {color: var(--default-letter);display: grid;font-size: 14px;line-height: 20px;gap: 8px;width: 100%;}input {box-sizing: border-box;width: 100%;color: var(--default-letter);border-color: var(--default-border);border-width: 2px;border-style: solid;border-radius: 5px;padding: 10px 14px;line-height: 24px;font-size: 16px;}input::placeholder {color: var(--default-border);}input:hover {border-color: var(--default-border-hover);}input:read-only,input:disabled {cursor: not-allowed;border-color: var(--border-default);background-color: var(--background-light-grey);}kol-alert {margin-top: var(--kolibri-spacing);display: block;}.kol-required span::after {content: "*";}',
  'KOL-BUTTON-GROUP':
    ':host {--kolibri-background-color: white;--kolibri-background-color-modal: rgba(0, 0, 0, 0.5);--kolibri-border-color: #aaaaaa;--kolibri-border-radius: 5px;--kolibri-border-width: 2px;--kolibri-color: black;--kolibri-color-undefined: #fb00d2;--kolibri-color-accent: #ef9e48;--kolibri-color-active: #1e538f;--kolibri-color-hover: #1e538f;--kolibri-color-focus: #1e538f;--kolibri-color-danger: #ad0e0b; /* --kolibri-color-dark: #222222; */--kolibri-color-error: #ad0e0b;--kolibri-color-ghost: #333333;--kolibri-color-info: #28568a; /* --kolibri-color-light: #f2f2f2; */--kolibri-color-normal: #326cae;--kolibri-color-outline: rgba(0, 0, 0, 0.5);--kolibri-color-primary: #1e538f;--kolibri-color-secondary: #444444;--kolibri-color-spin-1: #000000;--kolibri-color-spin-2: #ff0000;--kolibri-color-spin-3: #ffcc00;--kolibri-color-success: #12632f;--kolibri-color-warning: #854000;--kolibri-font-family: BundesSans, Calibri, Verdana, Arial, Helvetica,sans-serif;--kolibri-font-size: 16px;--kolibri-hyphens: auto;--kolibri-line-height: 1.5em;--kolibri-shadow-color: black;--kolibri-spacing: 0.25em;}:host {display: inline-flex;}div {display: flex;flex-wrap: wrap;padding: 0.25em;border-radius: 5px;gap: 0.25em;background-color: var(--kolibri-color-normal);}',
  GLOBAL:
    ':host {--kolibri-background-color: white;--kolibri-background-color-modal: rgba(0, 0, 0, 0.5);--kolibri-border-color: #aaaaaa;--kolibri-border-radius: 5px;--kolibri-border-width: 2px;--kolibri-color: black;--kolibri-color-undefined: #fb00d2;--kolibri-color-accent: #ef9e48;--kolibri-color-active: #1e538f;--kolibri-color-hover: #1e538f;--kolibri-color-focus: #1e538f;--kolibri-color-danger: #ad0e0b; /* --kolibri-color-dark: #222222; */--kolibri-color-error: #ad0e0b;--kolibri-color-ghost: #333333;--kolibri-color-info: #28568a; /* --kolibri-color-light: #f2f2f2; */--kolibri-color-normal: #326cae;--kolibri-color-outline: rgba(0, 0, 0, 0.5);--kolibri-color-primary: #1e538f;--kolibri-color-secondary: #444444;--kolibri-color-spin-1: #000000;--kolibri-color-spin-2: #ff0000;--kolibri-color-spin-3: #ffcc00;--kolibri-color-success: #12632f;--kolibri-color-warning: #854000;--kolibri-font-family: BundesSans, Calibri, Verdana, Arial, Helvetica,sans-serif;--kolibri-font-size: 16px;--kolibri-hyphens: auto;--kolibri-line-height: 1.5em;--kolibri-shadow-color: black;--kolibri-spacing: 0.25em;--spacing: 0.25em;--font-family: BundesSans, Calibri, Verdana, Arial, Helvetica, sans-serif;--font-size: 16px;}:host {font-family: var(--font-family);font-size: var(--font-size);}',
  'KOL-INPUT-PASSWORD':
    ':host {font-family: BundesSans;}:host input:focus {outline-color: var(--kolibri-color-outline) !important;outline-offset: 2px;outline-style: solid;outline-width: 3px;}label {color: var(--default-letter);display: grid;font-size: 14px;line-height: 20px;gap: 8px;width: 100%;}input {box-sizing: border-box;width: 100%;color: var(--default-letter);border-color: var(--default-border);border-width: 2px;border-style: solid;border-radius: 5px;padding: 10px 14px;line-height: 24px;font-size: 16px;}input::placeholder {color: var(--default-border);}input:hover {border-color: var(--default-border-hover);}input:read-only,input:disabled {cursor: not-allowed;border-color: var(--border-default);background-color: var(--background-light-grey);}kol-alert {margin-top: var(--kolibri-spacing);display: block;}.kol-required span::after {content: "*";}',
  'KOL-INPUT-NUMBER':
    ':host {font-family: BundesSans;}:host input:focus {outline-color: var(--kolibri-color-outline) !important;outline-offset: 2px;outline-style: solid;outline-width: 3px;}label {color: var(--default-letter);display: grid;font-size: 14px;line-height: 20px;gap: 8px;width: 100%;}input {box-sizing: border-box;width: 100%;color: var(--default-letter);border-color: var(--default-border);border-width: 2px;border-style: solid;border-radius: 5px;padding: 10px 14px;line-height: 24px;font-size: 16px;}input::placeholder {color: var(--default-border);}input:hover {border-color: var(--default-border-hover);}input:read-only,input:disabled {cursor: not-allowed;border-color: var(--border-default);background-color: var(--background-light-grey);}kol-alert {margin-top: var(--kolibri-spacing);display: block;}.kol-required span::after {content: "*";}',
  'KOL-INPUT-EMAIL':
    ':host {font-family: BundesSans;}:host input:focus {outline-color: var(--kolibri-color-outline) !important;outline-offset: 2px;outline-style: solid;outline-width: 3px;}label {color: var(--default-letter);display: grid;font-size: 14px;line-height: 20px;gap: 8px;width: 100%;}input {box-sizing: border-box;width: 100%;color: var(--default-letter);border-color: var(--default-border);border-width: 2px;border-style: solid;border-radius: 5px;padding: 10px 14px;line-height: 24px;font-size: 16px;}input::placeholder {color: var(--default-border);}input:hover {border-color: var(--default-border-hover);}input:read-only,input:disabled {cursor: not-allowed;border-color: var(--border-default);background-color: var(--background-light-grey);}kol-alert {margin-top: var(--kolibri-spacing);display: block;}.kol-required span::after {content: "*";}',
  'KOL-INPUT-FILE':
    ':host {font-family: BundesSans;}:host input:focus {outline-color: var(--kolibri-color-outline) !important;outline-offset: 2px;outline-style: solid;outline-width: 3px;}label {color: var(--default-letter);display: grid;font-size: 14px;line-height: 20px;gap: 8px;width: 100%;}input {box-sizing: border-box;width: 100%;color: var(--default-letter);border-color: var(--default-border);border-width: 2px;border-style: solid;border-radius: 5px;padding: 10px 14px;line-height: 24px;font-size: 16px;}input::placeholder {color: var(--default-border);}input:hover {border-color: var(--default-border-hover);}input:read-only,input:disabled {cursor: not-allowed;border-color: var(--border-default);background-color: var(--background-light-grey);}kol-alert {margin-top: var(--kolibri-spacing);display: block;}.kol-required span::after {content: "*";}',
  'KOL-TEXTAREA':
    ':host {font-family: BundesSans;}:host textarea:focus {outline-color: var(--kolibri-color-outline) !important;outline-offset: 2px;outline-style: solid;outline-width: 3px;}label {color: var(--default-letter);display: grid;font-size: 14px;line-height: 20px;gap: 8px;width: 100%;}textarea {box-sizing: border-box;width: 100%;color: var(--default-letter);border-color: var(--default-border);border-width: 2px;border-style: solid;border-radius: 5px;padding: 10px 14px;line-height: 24px;font-size: 16px;}textarea::placeholder {color: var(--default-border);}textarea:hover {border-color: var(--default-border-hover);}textarea:read-only,textarea:disabled {cursor: not-allowed;border-color: var(--border-default);background-color: var(--background-light-grey);}kol-alert {margin-top: var(--kolibri-spacing);display: block;}.kol-required span::after {content: "*";}',
  'KOL-HEADING':
    'h1,h2,h3,h4,h5,h6 {line-height: 1em;margin: 0;padding: 0;}h1 {font-size: 1.5rem;}h2 {font-size: 1.4rem;}h3 {font-size: 1.3rem;}h4 {font-size: 1.2rem;}h5 {font-size: 1.1rem;}h6 {font-size: 1rem;}',
});
