export const TAG_NAMES: string[] = [
  // 'kol-icon',

  // 'kol-icon-font-awesome',
  // 'kol-icon-icofont',

  'kol-badge',
  'kol-heading',

  'kol-accordion',
  'kol-alert',
  'kol-card',
  'kol-tooltip',
  'kol-version',

  'kol-abbr',
  'kol-button',
  'kol-button-group',
  'kol-indented-text',
  'kol-input-checkbox',
  'kol-input-color',
  'kol-input-file',
  'kol-input-email',
  'kol-input-number',
  'kol-input-password',
  'kol-input-radio',
  'kol-input-text',
  'kol-link',
  'kol-select',
  'kol-textarea',

  'kol-breadcrumb',
  'kol-details',
  'kol-form',
  // 'kol-input-adapter-leanup',
  'kol-kolibri',
  'kol-link-group',
  // 'kol-logo',
  'kol-modal',
  'kol-nav',
  'kol-progress',
  'kol-skip-nav',
  'kol-spin',
  'kol-table',
  'kol-tabs',
  'kol-toast',
];
